mysqldata:
  image: harshjv/mysql-data:0.9.16-1.0

composerdata:
  image: harshjv/composer-data:0.9.16-1.0

mysql:
  image: harshjv/mysql:0.9.16-1.0
  ports:
    - "3306:3306"
  environment:
    MYSQL_PASS: root
  volumes_from:
    - mysqldata
  volumes:
    - ./data:/var/lib/mysql

server:
  image: ovalbsol/edgecumbe
  volumes_from:
    - composerdata
  links:
    - mysql
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./build:/etc/apache2/sites-available
    - ./:/var/www/html
  container_name: oas

gulp:
  image: harshjv/bower-gulp:1.0
